apiVersion: apps/v1
kind: Deployment
metadata:
  name: apistone
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: api
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: api
    spec:
      containers:
      - name: {{ .Values.serviceName }}
        image: docker.io/softstone1/apistone:v1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 80
